(define writer
    (lambda (path values)
        (let ((port (open-output-file path)))
            (display "var words = [" port)
            (newline port)
            (let f ((ls values))
                (if (null? (cdr ls))
                    (begin
                        (display "{ text: " port)
                        (write (caar ls) port)
                        (display ", weight: " port)
                        (display (cadar ls) port)
                        (display "}" port)
                        (newline port))
                    (begin
                        (display "{ text: " port)
                        (write (caar ls) port)
                        (display ", weight: " port)
                        (display (cadar ls) port)
                        (display " }," port)
                        (newline port)
                        (f (cdr ls)))))
            (display "];" port)
            (close-output-port port))))